language: node_js
node_js:
  - 12
  - 10
  - 8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
cache: yarn
script:
  - yarn test:report
